<html>

<head>
<title>管理员登陆</title>
</head>

<body bgcolor="#F4FAED">
<p align="center" color="#669999"><img border="0" src="login.jpg" align="center" width="557" height="350">

<p align="center" color="#669999"><a href="main.asp?9">游客进入</a><div align="center">
  <center>
  <table border="1" width=430>
    <tr>
    <form action="checklogin.asp" method=post>
      <td width=80 align="center"><font color="#669999">管理员登陆</font></td>
      <td width=48 align="center"><font color="#669999">用户名</font></td>
      <td width=80 align="center">
 	<input type="text" name="username" size=10 id=username></td>
      <td width=32 align="center"><font color="#669999">密码</font> </td>
      <td width=80 align="center">
      <input type="password" name="password" size=10 id=password></td>
      <td width=32 align="center">
	<input type="submit" value="登陆" id="submit" name="submit"></td>
    </form>
    </tr>
  </table>
  </center>
</div>

</body>

</html>
